{
 "title": "Kubernetes Development Dashboard",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_spec_unschedulable, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": " Development Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 0, "y": 1 } },
    { "title": " Development 2 Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 6, "y": 1 } },
    { "title": " UAT Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 12, "y": 1 } },
    {
     "title": "kubernetes ISR Development Alerts",
     "type": "alertlist",
     "gridPos": { "h": 18, "w": 6, "x": 18, "y": 1 }
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Down",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Nodes List",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 2 },
     "targets": [
      {
       "expr": "kube_node_spec_unschedulable{node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\", node=~\"$node\"}) / sum (machine_memory_bytes{node=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU Usage (1m avg)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$node\"}[1m])) / sum (machine_cpu_cores{node=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "Filesystem Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"$node\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"$node\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU Core Request/Total/Limit For $node Worker Node",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Core" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",node=~\"$node\"})",
       "legendFormat": "Request CPU"
      },
      {
       "expr": "sum(kube_node_status_allocatable_cpu_cores{namespace=~\"$namespace\",node=~\"$node\"})",
       "legendFormat": "Total CPU"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",node=~\"$node\"})",
       "legendFormat": "Limit CPU"
      }
     ]
    },
    {
     "title": "Memory Request/Total/Limit For $node Worker Node",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",node=~\"$node\"})",
       "legendFormat": "Request Memory"
      },
      {
       "expr": "sum(kube_node_status_allocatable_memory_bytes{namespace=~\"$namespace\",node=~\"$node\"})",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",node=~\"$node\"})",
       "legendFormat": "Limit Memory"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$node\"}[1m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Network I/O Pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{node=~\"$node\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"$node\"}[1m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Quotas",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(mixin_pod_workload) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
      },
      {},
      {
       "expr": "sum(container_memory_rss{container!=\"\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Istio Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unavailable pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"istio-system\"})"
      }
     ]
    },
    {
     "title": "Unavailable Pods History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"istio-system\"}) by ( deployment) ",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Istio CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"istio-system\"}[5m] ) )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Istio Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_memory_usage_bytes{image!=\"\", namespace=~\"istio-system\"}[5m] ) )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Istio Filesystem Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_fs_usage_bytes{namespace=~\"istio-system\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unavailable Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"logging\"})"
      }
     ]
    },
    {
     "title": "Unavailable Pods History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"logging\"}) by ( deployment) ",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Logging CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"logging\"}[5m] ) )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logging Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_memory_usage_bytes{image!=\"\", namespace=~\"logging\"}[5m] ) )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Logging Filesystem Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_fs_usage_bytes{namespace=~\"logging\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unavailable Pods",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"monitoring\"})"
      }
     ]
    },
    {
     "title": "Unavailable Pods History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"monitoring\"}) by ( deployment) ",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Monitoring CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"monitoring\"}[5m] ) )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Monitoring Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_memory_usage_bytes{image!=\"\", namespace=~\"monitoring\"}[5m] ) )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Monitoring Filesystem Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod)( rate(container_fs_usage_bytes{namespace=~\"monitoring\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total of Pods Available",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployments with unavailable Pods",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 16, "w": 20, "x": 4, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"}) by ( deployment, namespace)",
       "legendFormat": "{{deployment}} [{{namespace}}]"
      }
     ]
    },
    {
     "title": "Total of Pods not Available",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) by (pod, namespace) > 0",
       "legendFormat": "{{namespace}} -> {{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",node=~\"$node\",namespace=~\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"$node\",namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"$node\",namespace=~\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "-> {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}